import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const hanken = Hanken_Grotesk({ 
  subsets: ['latin'],
  weight: ['500', '700', '800'],
  variable: '--font-hanken' // Esta variable conecta con el tailwind.config.js
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${hanken.variable} h-full antialiased`}
    >
      <body className="bg-gray-100 flex items-center justify-center min-h-screen antialiased">{children}</body>
    </html>
  );
}
